name: PiCar-X PR Build (RPI4)

on: [pull_request, workflow_dispatch]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.sha }}

      - name: build core container
        working-directory: ./PiCar-X
        run: |
          TAG=${{ github.sha }} ARCH=arm64v8 docker compose -f docker-compose-core.yml build --no-cache

      - name: build dtp containers without gazebo
        working-directory: ./PiCar-X
        run: |
          TAG=${{ github.sha }} ARCH=arm64v8 docker compose -f docker-compose-dtp-no-gazebo.yml build --no-cache

  unit-tests:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.sha }}
          
      - name: Run pytest in Docker container
        working-directory: ./PiCar-X
        run: |
          docker run --rm --name picarx-unittest ghcr.io/cau-se/arches-picar-x/picarx:${{ github.sha }} pytest ./src/core/picarx/tests

  integration-tests:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.sha }}

      - name: Integration Test dcmotor
        working-directory: ./PiCar-X
        run: |
          docker run --rm --name dcmotor-integration-test -v /sys/class/gpio:/sys/class/gpio -v /dev/i2c-11:/dev/i2c-11 --privileged  ghcr.io/cau-se/arches-picar-x/drivers/dcmotor:${{ github.sha }} rostest picarx_dcmotor_driver integration_tests.test i2c_port:=/dev/i2c-11
