name: PiCar-X Main Build on PUSH (RPI3)

on:
  push:
    branches:
      - main
    paths:
      - PiCar-X/**
      - .github/workflows/**.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM]

    steps:
      - uses: actions/checkout@v4

      - name: build core container
        working-directory: ./PiCar-X
        run: |
          TAG=latest-arm32v7 ARCH=arm32v7 docker compose -f docker-compose-core.yml build --no-cache

      - name: build dtp containers without gazebo
        working-directory: ./PiCar-X
        run: |
          TAG=latest-arm32v7 ARCH=arm32v7 docker compose -f docker-compose-dtp-no-gazebo.yml build --no-cache

  unit-tests:
    runs-on: [self-hosted, Linux, ARM]
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Run pytest in Docker container
        working-directory: ./PiCar-X
        run: |
          docker run --rm --name picarx-unittest ghcr.io/cau-se/arches-picar-x/picarx:latest-arm32v7 pytest ./src/core/picarx/tests

  integration-tests:
    runs-on: [self-hosted, Linux, ARM]
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Integration Test dcmotor
        working-directory: ./PiCar-X
        run: |
          docker run --rm --name dcmotor-integration-test -v /sys/class/gpio:/sys/class/gpio -v /dev/i2c-11:/dev/i2c-11 --privileged  ghcr.io/cau-se/arches-picar-x/drivers/dcmotor:latest-arm32v7 rostest picarx_dcmotor_driver integration_tests.test i2c_port:=/dev/i2c-11

  release:
    runs-on: [self-hosted, Linux, ARM]
    needs: [integration-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to ghcr.io
        working-directory: ./PiCar-X
        run: |
          TAG=latest-arm32v7 docker compose -f docker-compose-dtp-no-gazebo.yml push
